trigger:
- main

pool:
  name: 'Default'

steps:
- script: |
    echo "--- Compiling and Forcing ROOT status ---"
    javac test.java
    # We rename the file to ROOT.war so Azure makes it the homepage
    jar cvf ROOT.war index.html *.class
  displayName: 'Compile and Package as ROOT'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'LabConnectionFinal'
    appType: 'webAppLinux'
    WebAppName: 'fatimah-devops-lab'
    # Use the new ROOT name here
    packageForLinux: '$(System.DefaultWorkingDirectory)/ROOT.war'