trigger:
- main

pool:
  name: 'Default'

steps:
- script: |
    echo "--- Compiling Java ---"
    javac test.java
    
    echo "--- Creating Package ---"
    # This command creates the war file with index.html 
    # and any .class files that were just created.
    jar cvf sample.war index.html *.class
  displayName: 'Compile and Package Java'
  continueOnError: true 

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'LabConnectionFinal'
    appType: 'webAppLinux'
    WebAppName: 'fatimah-devops-lab'
    packageForLinux: '$(System.DefaultWorkingDirectory)/sample.war'